### ISSUE TITLE
nan values after domain_show

### ISSUE THREAD

**Issue by xiaxilin** [mingxiaodong/hipims_io_python#1]
After calling the domain_show functions, two lines of DEM array becomes NaN. Then the dimension of the written DEM file does not match those of field data, which will lead to segmentation fault when running the model.

**Comment by mingxiaodong** [comment]
We wrongly used 'copy' instead of 'deepcopy' when trying to rectify DEM array to show the splitted domain of multi-gpu models by making cells on the split lines as nan. So, once we call domain_show function, the original DEM array was rectified rather than the copied one and that caused the problem of passing nan values to the input file z.dat.
Problem has been solved.
